services:
  yggdrasil_core:
    container_name: Yggdrasil_Core
    build: ./Yggdrasil_Core
    ports:
      - "8000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./.env:/app/.env:ro
    restart: always
    networks:
      - yggdrasil
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:latest
    container_name: redis
    command:
      redis-server 
      --requirepass ${REDIS_PASS} 
    restart: always
    ports:
      - "6379"
    networks:
      - yggdrasil

  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DATABASE}    
      MYSQL_USER: ${DB_USER}             
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    restart: always
    networks:
      - yggdrasil
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - "8000:8000"
      - "6379:6379"
      - "3306:3306"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/scripts:/etc/nginx/scripts:ro
    restart: always
    depends_on:
      - yggdrasil_core
    networks:
      - yggdrasil

networks:
  yggdrasil:
    driver: bridge